---
apiVersion: v1
kind: Namespace
metadata:
  name: my-php-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: my-php-app
  name: deployment-phptest
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: phptest
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phptest
    spec:
      containers:
      - image: xxxx.dkr.ecr.us-east-1.amazonaws.com/php-test:latest
        imagePullPolicy: Always
        name: phptest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: my-php-app
  name: service-phptest
spec:
  ports:
    - port: 30080
      targetPort: 80
      nodePort: 30010
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: phptest